server:
  port:8034

spring:
  application:
     name:cloud-service

spring:
  profiles:
     active:native
  cloud:
    config:
      server:
        native:
          searchLocations:
